version: '3'
services:
  frontend:
    container_name: frontend
    image: bigkungcup/frontend
    ports:
      - 3000:3000
    networks:
      - oasip-network
    restart: always

networks:
  oasip-network:
    external:
     name: oasip-network