version: '3.7'
services:
  proxy:
    container_name: reverse_proxy
    image: nginx
    ports:
      - 80:80
    networks:
      - oasip-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/ip21kw4.crt:/etc/nginx/ssl/ip21kw4.cet
      - ./cert/ip21kw4.key:/etc/nginx/ssl/ip21kw4.key
    restart: always

networks:
  oasip-network:
    external:
     name: oasip-network