version: '3.7'
services:
  proxy:
    container_name: reverse_proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - oasip-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/spadmin/clinic/INT_222_04/Nginx/cert/ip21kw4.crt:/etc/ssl/ip21kw4.cet
      - /home/spadmin/clinic/INT_222_04/Nginx/cert/ip21kw4.key:/etc/ssl/ip21kw4.key
    restart: always

networks:
  oasip-network:
    external:
     name: oasip-network