version: '3.7'
services:
  proxy:
    container_name: reverse_proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - oasip-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/:/etc/nginx/ssl:ro
    restart: always

networks:
  oasip-network:
    external:
     name: oasip-network