name: CI

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # Runs a Database  
      - name: Database Docker Compose Down and Remove Images
        run: |
          cd Database
          sudo docker-compose down
          sudo docker rmi -f mysql
          sudo docker-compose up -d --build
          sudo docker image prune -f
          cd ..

      # Runs a Back-end
      - name: Back-end Docker Compose Down and Remove Images
        run: |
          cd Backend
          sudo docker-compose down
          sudo docker rmi -f backend
          sudo docker-compose up -d --build
          sudo docker image prune -f
          cd ..
      
      # Runs a Front-end
      - name: Front-end Docker Compose Down and Remove Images
        run: |
          cd Frontend
          sudo docker-compose down
          sudo docker rmi -f frontend
          sudo docker-compose up -d --build
          sudo docker image prune -f
          cd ..

      # Runs a Reverse-Proxy
      - name: Reverse-Proxy Docker Compose Down
        run: |
          cd Nginx
          sudo docker-compose down
          sudo docker-compose up -d --build
          sudo docker image prune -f
          cd ..
